### ISSUE TITLE
Cookies stored in session when consent-cookie-options but expirationDate not defined

### ISSUE THREAD

**Issue by lkappeler** [jvandemo/angular-consent#4]
If you set the consent-cookie-options option but not define 'expires' the cookie gets stored in the session.

See: https://github.com/jvandemo/angular-consent/blob/master/dist/angular-consent.js#L56

**Comment by jvandemo** [comment]
@lkappeler &mdash; Just released v2.1.1 with a fix. Thank you for reporting! Much appreciated! 👍
